title: <p align="center"> Kuldeep </p>
logo: /assets/img/logo.png
description: 

<br>
I'm currently doing certification in ML and AI
<br>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
